jar:
	javac *.java edu/stanford/nlp/*/*.java edu/stanford/nlp/*/*/*.java
	jar cf RSNL.jar *.class edu/
	mv RSNL.jar ../inst/java/

clean:
	rm *.class
	rm edu/stanford/nlp/*/*.class
	rm edu/stanford/nlp/*/*/*.class
	rm edu/stanford/nlp/*/*/*/*.class
